### ISSUE TITLE
Gradle build issue 

### ISSUE THREAD

**Issue by kche309** [bioDS/beast-phylonco#28]
An error occurs when importing as a new Gradle project in Intellij:
```
A problem occurred configuring project ':phylonco-lphy'.
> Extension of type 'PublishingExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension]

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':phylonco-lphy'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:75)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:68)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$400(LifecycleProjectEvaluator.java:51)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.lambda$run$0(LifecycleProjectEvaluator.java:105)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.lambda$applyToMutableState$0(DefaultProjectStateRegistry.java:366) 

...

```

**Comment by walterxie** [comment]
The error message shows you have not installed Gradle plugin `maven-publish` https://docs.gradle.org/current/userguide/publishing_maven.html , which is weird. The build file contains https://github.com/bioDS/beast-phylonco/blob/3ce0885da53ffd329239d6ba3efe717fc580718a/phylonco-lphy/build.gradle.kts#L3. Can you please try to run build in the command line first and load the project into IntelliJ?

**Comment by kche309** [comment]
@walterxie thanks, re-building on command line before loading in Intellij solved the issue.
