### ISSUE TITLE
Migrate to LPhy 1.3.1 and LPhyBeast 0.4.2

### ISSUE THREAD

**Issue by walterxie** [bioDS/beast-phylonco#29]
LPhy 1.3.0 is a major update: https://github.com/LinguaPhylo/linguaPhylo/releases/tag/1.3.0

LPhyBeast 0.4.1 has less BEAST2 packages to depend on: https://github.com/LinguaPhylo/LPhyBeast/releases

Update to LPhy 1.3.1 and LPhyBeast 0.4.2

**Comment by walterxie** [comment]
all tests are passed

**Comment by kche309** [comment]
Hi @walterxie I'm getting an error when running the LPhy script https://github.com/bioDS/beast-phylonco/blob/lphy1.3/phylonco-lphy/examples/simpleRelaxedError.lphy using gradle task `runLPhyStudio` from the lphy1.3 branch. 

Could you help me check whether this script works from your end? 

```
lphy.parser.ParserUtils constructGenerator
SEVERE: Parsing generator GT16ErrorModel failed.
lphy.parser.ParserUtils constructGenerator
SEVERE: Parsing generator GT16ErrorModel failed.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "lphy.graphicalModel.Generator.setInput(String, lphy.graphicalModel.Value)" because "generator" is null
	at lphy@1.3.0/lphy.parser.SimulatorListenerImpl$SimulatorASTVisitor.visitDistribution(SimulatorListenerImpl.java:557)
	at lphy@1.3.0/lphy.parser.SimulatorParser$DistributionContext.accept(SimulatorParser.java:1256)
	at org.antlr.antlr4.runtime@4.9.3/org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at lphy@1.3.0/lphy.parser.SimulatorListenerImpl$SimulatorASTVisitor.visitStoch_relation(SimulatorListenerImpl.java:191)
	at lphy@1.3.0/lphy.parser.SimulatorListenerImpl$SimulatorASTVisitor.visitStoch_relation(SimulatorListenerImpl.java:67)
	at lphy@1.3.0/lphy.parser.SimulatorParser$Stoch_relationContext.accept(SimulatorParser.java:607)
	at org.antlr.antlr4.runtime@4.9.3/org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at lphy@1.3.0/lphy.parser.SimulatorBaseVisitor.visitRelation(SimulatorBaseVisitor.java:41)
	at lphy@1.3.0/lphy.parser.SimulatorParser$RelationContext.accept(SimulatorParser.java:324)
	at org.antlr.antlr4.runtime@4.9.3/org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at lphy@1.3.0/lphy.parser.SimulatorBaseVisitor.visitRelation_list(SimulatorBaseVisitor.java:34)
	at lphy@1.3.0/lphy.parser.SimulatorParser$Relation_listContext.accept(SimulatorParser.java:240)
	at org.antlr.antlr4.runtime@4.9.3/org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at lphy@1.3.0/lphy.parser.SimulatorBaseVisitor.visitInput(SimulatorBaseVisitor.java:20)
	at lphy@1.3.0/lphy.parser.SimulatorParser$InputContext.accept(SimulatorParser.java:131)
	at org.antlr.antlr4.runtime@4.9.3/org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at lphy@1.3.0/lphy.parser.SimulatorListenerImpl.parse(SimulatorListenerImpl.java:928)
	at lphy@1.3.0/lphy.parser.REPL.parse(REPL.java:102)
	at lphy@1.3.0/lphy.core.GraphicalLPhyParser.parse(GraphicalLPhyParser.java:53)
	at lphystudio@1.3.0/lphystudio.app.graphicalmodelpanel.GraphicalModelInterpreter.interpretInput(GraphicalModelInterpreter.java:230)
	at lphystudio@1.3.0/lphystudio.app.graphicalmodelpanel.GraphicalModelPanel.source(GraphicalModelPanel.java:199)
	at lphystudio@1.3.0/lphystudio.app.Utils.readFile(Utils.java:130)
	at lphystudio@1.3.0/lphystudio.app.Utils.readFileFromDir(Utils.java:104)
...
```

**Comment by walterxie** [comment]
No problem in my IntelliJ, can you check if your libs were updated? If not, follow https://github.com/LinguaPhylo/LPhyBeast/blob/master/DEV_NOTE.md to update your dependencies' local repo.

<img width="514" alt="Screen Shot 2022-08-08 at 10 14 35 AM" src="https://user-images.githubusercontent.com/5743014/183313050-95b2f6c7-3436-4cb1-845b-55a5bd73f94b.png">

**Comment by walterxie** [comment]
<img width="1712" alt="Screen Shot 2022-08-08 at 10 17 59 AM" src="https://user-images.githubusercontent.com/5743014/183313147-52520a72-0157-4262-9cb1-146f4462b9e7.png">

<img width="1712" alt="Screen Shot 2022-08-08 at 10 18 31 AM" src="https://user-images.githubusercontent.com/5743014/183313166-32c07fa7-6918-4428-b0f8-a14fb170ccf5.png">

**Comment by kche309** [comment]
Tested LPhy v1.3.1 compatible version on Intellij. 
Pull request looks good to merge.
